// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr'
const spec_Word = {
  __proto__: null,
  CONTAINS: 72,
  contains: 74,
  REGEXP: 76,
  regexp: 78,
  IN: 80,
  in: 82,
  NOT: 84,
  not: 86,
  NULL: 98,
  null: 100,
  NIL: 102,
  nil: 104,
  AND: 106,
  and: 108,
  OR: 110,
  or: 112,
  '|': 114,
  LIMIT: 116,
  limit: 118,
}
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "'OOkQPOOOVQPO'#C_OrQPO'#CaOOQO'#Cm'#CmO!vQPO'#C`OOQO'#Cn'#CnOOQO'#C|'#C|O#eQPO'#C^OOQO'#C{'#C{OOQO'#Ct'#CtO#yQPO'#CsOOQO'#C^'#C^QOQPOOO$RQPO,58yOOQO'#Ce'#CeOOQO'#Cf'#CfOOQO'#Cg'#CgOOQO'#Ci'#CiO$dQPO'#ChOOQO'#Cd'#CdOOQO'#DP'#DPO$rQPO,58zOOQO'#Cp'#CpOVQPO,59ZOOQO'#Cr'#CrOVQPO,59]OOQO,58x,58xOOQO'#Cu'#CuO%ZQPO,59_OOQO1G.e1G.eOOQO,59S,59SOOQO,59U,59UO%`QPO'#ClOOQO'#DY'#DYOOQO1G.f1G.fOOQO1G.u1G.uO%gQPO1G.wOOQO'#Cv'#CvOOQO1G.y1G.yO&OQPO'#D[O&WQPO,59WO$rQPO'#CwO&]QPO,59vOOQO1G.r1G.rOOQO,59c,59cOOQO-E6u-E6u",
  stateData:
    '&j~OnOS~OUQOqPO!RRO!SRO!TRO!URO~O!ZXO~PVOVTXlbXtTXuTXvTXwTXxTXyTXzTX{TX!VbX!WbX!XbX!YbX!ZbXrbX~OVdOt^Ou^Ov_Ow_Ox`Oy`OzaO{aO~O!VfO!WfO!XhO!YhO!ZXOlQX~O![kO!]kO~OrmO!VfO!WfO!XhO!YhO~Ot^Ou^Ox`Oy`O~OUqO_qO}pO!RRO!SRO!TRO!URO~OUuO~O!Q!OP~P$rO!VfO!WfOlei!Xei!Yei!Zeirei~O!PyO!Q!OX~O!Q{O~O!PyO!Q!Oa~O_VUV~',
  goto: '$j!PPP!Q!T!T!ZPP!a!d!j!m!j!s!jP!v!{!T#W#^#W#c#g#m#q#t#wPPP#}#WPP$ZPPPPPPPP$^P$gR[OXUOPgiXSOPgiRdSQcSRnbRcSQcSRobRbSVqepyWTOPgiVqepyXWOPgiVgV]tTiV]QZORjVTYOVRlYRvlQzwR}zQVOQ]PQsgRtiReSQreQwpR|yRxp',
  nodeNames:
    '⚠ Query SearchRequest Group Comparison FieldName Word Operator KeywordOperator Contains Regexp In NotContains Not NotIn QuotedString Array Null FreeText AndExpression And OrExpression Or LimitClause ModifierPipe Limit LimitValue',
  maxTerm: 59,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "*Y~RzX^#upq#uqr$jrs$xst&ftu$suv&fvw&fwx'vxy)_yz)dz{&f{|&f|})i}!O&f!O!P&f!P!Q&f!Q![&f![!]&f!^!_)n!_!`)v!`!a)n!a!b&f!b!c&f!c!}&f!}#O*O#O#P&f#P#Q*T#Q#R$s#R#S&f#T#o&f#o#p&f#p#q&f#q#r&f#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYn~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$mQ!_!`$s#r#s$s~$xOV~~${VOr$xrs%bs#O$x#O#P%g#P;'S$x;'S;=`&`<%lO$x~%gO_~~%jRO;'S$x;'S;=`%s;=`O$x~%vWOr$xrs%bs#O$x#O#P%g#P;'S$x;'S;=`&`;=`<%l$x<%lO$x~&cP;=`<%l$x~&kcU~st&fuv&fvw&fz{&f{|&f}!O&f!O!P&f!P!Q&f!Q![&f![!]&f!a!b&f!b!c&f!c!}&f#O#P&f#R#S&f#T#o&f#o#p&f#p#q&f#q#r&f~'yVOw'vwx%bx#O'v#O#P(`#P;'S'v;'S;=`)X<%lO'v~(cRO;'S'v;'S;=`(l;=`O'v~(oWOw'vwx%bx#O'v#O#P(`#P;'S'v;'S;=`)X;=`<%l'v<%lO'v~)[P;=`<%l'v~)dOq~~)iOr~~)nO!P~~)sPV~!_!`$s~){PV~#r#s$s~*TO}~~*YO!Q~",
  tokenizers: [0],
  topRules: { Query: [0, 1] },
  specialized: [
    {
      term: 6,
      get: (value: string) => spec_Word[value as keyof typeof spec_Word] || -1,
    },
  ],
  tokenPrec: 251,
})
