// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr'
const spec_Word = {
  __proto__: null,
  CONTAINS: 62,
  contains: 64,
  REGEXP: 66,
  regexp: 68,
  IN: 70,
  in: 72,
  NOT: 74,
  not: 76,
  NULL: 88,
  null: 90,
  NIL: 92,
  nil: 94,
  AND: 96,
  and: 98,
  OR: 100,
  or: 102,
}
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "%vOVQPOOOVQPO'#C^OkQPO'#C`OOQO'#Cl'#ClO!lQPO'#C_OOQO'#Cm'#CmOOQO'#Cw'#CwQ#ZQPOOOOQO'#Cv'#CvO#iQPO,58xOOQO'#Cd'#CdOOQO'#Ce'#CeOOQO'#Cf'#CfOOQO'#Ch'#ChO#zQPO'#CgOOQO'#Cc'#CcOOQO'#Cz'#CzO$YQPO,58yOOQO'#Co'#CoOVQPO,59YOOQO'#Cq'#CqOVQPO,59[OOQO1G.d1G.dOOQO,59R,59ROOQO,59T,59TO$qQPO'#CkOOQO'#DT'#DTOOQO1G.e1G.eOOQO1G.t1G.tO$xQPO1G.vO%^QPO'#DVO%fQPO,59VO$YQPO'#CrO%kQPO,59qOOQO1G.q1G.qOOQO,59^,59^OOQO-E6p-E6p",
  stateData:
    '%x~OiOS~OTQOlPO|RO}RO!ORO!PRO~OUSXgaXoSXpSXqSXrSXsSXtSXuSXvSX!QaX!RaX!SaX!TaXmaX~OU`OoYOpYOqZOrZOs[Ot[Ou]Ov]O~O!QbO!RbO!SdO!TdO~OmfO!QbO!RbO!SdO!TdO~OoYOpYOs[Ot[O~OTjO^jOxiO|RO}RO!ORO!PRO~O{yP~P$YO!QbO!RbOgdi!Sdi!Tdimdi~OzpO{yX~O{rO~OzpO{ya~O^UTU~',
  goto: '$QzPP{{!RPP!X![!b!e!b!k!bP!n!s{#O#U#O#Z#_PPP#e#OPP#qPPPPPPPP#tP#}XUOPceXSOPceR`SQ_SRg^R_SQ_SRh^R^SVjaipWTOPceVjaipXWOPceVcVXmTeVXQqnRtqQVOQXPQlcRmeRaSQkaQniRspRoi',
  nodeNames:
    '⚠ Query Group Comparison FieldName Word Operator KeywordOperator Contains Regexp In NotContains Not NotIn QuotedString Array Null FreeText AndExpression And OrExpression Or',
  maxTerm: 51,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "*Y~RzX^#upq#uqr$jrs$xst&ftu$suv&fvw&fwx'vxy)_yz)dz{&f{|&f|})i}!O&f!O!P&f!P!Q&f!Q![&f![!]&f!^!_)n!_!`)v!`!a)n!a!b&f!b!c&f!c!}&f!}#O*O#O#P&f#P#Q*T#Q#R$s#R#S&f#T#o&f#o#p&f#p#q&f#q#r&f#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYi~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$mQ!_!`$s#r#s$s~$xOU~~${VOr$xrs%bs#O$x#O#P%g#P;'S$x;'S;=`&`<%lO$x~%gO^~~%jRO;'S$x;'S;=`%s;=`O$x~%vWOr$xrs%bs#O$x#O#P%g#P;'S$x;'S;=`&`;=`<%l$x<%lO$x~&cP;=`<%l$x~&kcT~st&fuv&fvw&fz{&f{|&f}!O&f!O!P&f!P!Q&f!Q![&f![!]&f!a!b&f!b!c&f!c!}&f#O#P&f#R#S&f#T#o&f#o#p&f#p#q&f#q#r&f~'yVOw'vwx%bx#O'v#O#P(`#P;'S'v;'S;=`)X<%lO'v~(cRO;'S'v;'S;=`(l;=`O'v~(oWOw'vwx%bx#O'v#O#P(`#P;'S'v;'S;=`)X;=`<%l'v<%lO'v~)[P;=`<%l'v~)dOl~~)iOm~~)nOz~~)sPU~!_!`$s~){PU~#r#s$s~*TOx~~*YO{~",
  tokenizers: [0],
  topRules: { Query: [0, 1] },
  specialized: [
    {
      term: 5,
      get: (value: string) => spec_Word[value as keyof typeof spec_Word] || -1,
    },
  ],
  tokenPrec: 219,
})
