version: 2

env:
  - CGO_ENABLED=1

builds:
  - id: linux
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: [linux]
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ignore:
      - goos: darwin

  - id: darwin
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: [darwin]
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ignore:
      - goos: linux

archives:
  - id: otel-desktop-viewer-archive
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

# brews:
#   - name: otel-desktop-viewer
#     tap:
#       owner: CtrlSpice
#       name: homebrew-tap
#     homepage: https://github.com/CtrlSpice/otel-desktop-viewer
#     description: OpenTelemetry Desktop Viewer
#     license: MIT
#     test: |
#       system "#{bin}/otel-desktop-viewer", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
