version: 2

before:
  hooks:
    - name: Update exporter dependency
      run: |
        cd desktopcollector
        go get github.com/CtrlSpice/otel-desktop-viewer/desktopexporter@latest
        go mod tidy

env:
  - CGO_ENABLED=1

builds:
  - id: linux-amd64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: linux
    goarch: amd64
    env:
      - CGO_ENABLED=1

  - id: linux-arm64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: linux
    goarch: arm64
    env:
      - CGO_ENABLED=1

  - id: darwin-amd64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: darwin
    goarch: amd64
    env:
      - CGO_ENABLED=1

  - id: darwin-arm64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: darwin
    goarch: arm64
    env:
      - CGO_ENABLED=1

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - name: otel-desktop-viewer
    tap:
      owner: CtrlSpice
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/CtrlSpice/otel-desktop-viewer
    description: OpenTelemetry Desktop Viewer
    license: MIT
    test: |
      system "#{bin}/otel-desktop-viewer", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
