version: 2

env:
  - CGO_ENABLED=1

before:
  hooks:
    - cmd: go work sync
    - cmd: sh -c "cd desktopcollector && go mod tidy && cd ../desktopexporter && go mod tidy"

builds:
  - id: macos_intel
    main: ./desktopcollector/
    # Using simple binary name as GoReleaser automatically creates unique directories
    # with build ID and target info (e.g. macos-intel_darwin_amd64)
    binary: otel-desktop-viewer
    goos: 
      - darwin
    goarch:
      - amd64
    # Sets binary timestamp to commit time for reproducible builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    # Removes file paths from binary for security and portability
    flags:
      - -trimpath
    # -s -w: strips debug info
    # -X: injects version, commit, and date into binary
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

  - id: macos_silicon
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos: 
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

  - id: linux_x86_64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

  - id: linux_arm64
    main: ./desktopcollector/
    binary: otel-desktop-viewer
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

archives:
  - id: otel-desktop-viewer-archive
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "v{{ .Version }}"
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
