// Started life generated by "go.opentelemetry.io/collector/cmd/builder", and is
// maintained by hand now. Edit it.
//
// There is no builder manifest in this repo, so nothing can regenerate it: the
// duckdb extension was added here by hand, and running ocb would want to own
// main.go too -- the CLI flags, collectorURIs, the browser-port wiring, the
// startup error handling. None of that came from the builder.
//
// The versions below are therefore a second copy of what go.mod pins, and they
// drifted once already: a dependency bump left this file naming v0.157.0 in a
// binary built against v0.158.0, so `otel-desktop-viewer components` reported a
// version that was not there. TestComponentModuleVersionsMatchGoMod compares
// the two now, so the next bump fails rather than lying quietly.

package main

import (
	desktopexporter "github.com/CtrlSpice/otel-desktop-viewer/desktopexporter"
	duckdbextension "github.com/CtrlSpice/otel-desktop-viewer/desktopexporter/duckdbextension"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/connector"
	"go.opentelemetry.io/collector/otelcol"
	batchprocessor "go.opentelemetry.io/collector/processor/batchprocessor"
	otlpreceiver "go.opentelemetry.io/collector/receiver/otlpreceiver"
	"go.opentelemetry.io/collector/service/telemetry/otelconftelemetry"
)

func components() (otelcol.Factories, error) {
	var err error
	factories := otelcol.Factories{}

	// Required since collector v0.135: the service telemetry providers
	// (logger, metrics, traces for the collector itself) come from an
	// explicit factory instead of being built implicitly.
	factories.Telemetry = otelconftelemetry.NewFactory()

	factories.Extensions, err = otelcol.MakeFactoryMap(
		duckdbextension.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}
	factories.ExtensionModules = make(map[component.Type]string, len(factories.Extensions))
	factories.ExtensionModules[duckdbextension.NewFactory().Type()] = "github.com/CtrlSpice/otel-desktop-viewer/desktopexporter/duckdbextension"

	factories.Receivers, err = otelcol.MakeFactoryMap(
		otlpreceiver.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}
	factories.ReceiverModules = make(map[component.Type]string, len(factories.Receivers))
	factories.ReceiverModules[otlpreceiver.NewFactory().Type()] = "go.opentelemetry.io/collector/receiver/otlpreceiver v0.158.0"

	factories.Exporters, err = otelcol.MakeFactoryMap(
		desktopexporter.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}
	factories.ExporterModules = make(map[component.Type]string, len(factories.Exporters))
	factories.ExporterModules[desktopexporter.NewFactory().Type()] = "github.com/CtrlSpice/otel-desktop-viewer/desktopexporter"

	factories.Processors, err = otelcol.MakeFactoryMap(
		batchprocessor.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}
	factories.ProcessorModules = make(map[component.Type]string, len(factories.Processors))
	factories.ProcessorModules[batchprocessor.NewFactory().Type()] = "go.opentelemetry.io/collector/processor/batchprocessor v0.158.0"

	factories.Connectors, err = otelcol.MakeFactoryMap[connector.Factory]()
	if err != nil {
		return otelcol.Factories{}, err
	}
	factories.ConnectorModules = make(map[component.Type]string, len(factories.Connectors))

	return factories, nil
}
