receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318

processors:

exporters:
  desktop:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - desktop