// I have edited the code generated by "go.opentelemetry.io/collector/cmd/builder".
// Pray I don't edit it any further.
// Program otel-desktop-viewer is an OpenTelemetry Collector binary.

package main

import (
	"log"
	"net"
	"strconv"
	"time"

	"github.com/pkg/browser"
	"github.com/spf13/cobra"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	yamlprovider "go.opentelemetry.io/collector/confmap/provider/yamlprovider"
	"go.opentelemetry.io/collector/otelcol"
)

var version = "dev" // This will be set by ldflags during build

func main() {
	info := component.BuildInfo{
		Command:     "otel-desktop-viewer",
		Description: "Collector distribution that allows developers to visualize their OTel data locally",
		Version:     version,
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
			},
		},
	}

	if err := run(set); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := newCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}

func newCommand(set otelcol.CollectorSettings) *cobra.Command {
	var httpPortFlag, grpcPortFlag, browserPortFlag int
	var hostFlag, dbFlag string
	var openBrowserFlag bool

	rootCmd := &cobra.Command{
		Use:     set.BuildInfo.Command,
		Version: set.BuildInfo.Version,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Format the host for use in endpoint addresses.
			// IPv6 addresses must be wrapped in brackets for net.JoinHostPort
			// and YAML values containing special characters need quoting.
			endpoint := formatEndpoint(hostFlag)

			set.ConfigProviderSettings.ResolverSettings.URIs = []string{
				`yaml:receivers::otlp::protocols::http::cors::allowed_origins: [https://*,http://*]`,
				`yaml:receivers::otlp::protocols::http::endpoint: "` + endpoint(httpPortFlag) + `"`,
				`yaml:receivers::otlp::protocols::grpc::endpoint: "` + endpoint(grpcPortFlag) + `"`,
				`yaml:exporters::desktop::endpoint: "` + endpoint(browserPortFlag) + `"`,
				`yaml:exporters::desktop::db: ` + dbFlag,
				`yaml:service::pipelines::traces::receivers: [otlp]`,
				`yaml:service::pipelines::traces::exporters: [desktop]`,
				`yaml:service::pipelines::metrics::receivers: [otlp]`,
				`yaml:service::pipelines::metrics::exporters: [desktop]`,
				`yaml:service::pipelines::logs::receivers: [otlp]`,
				`yaml:service::pipelines::logs::exporters: [desktop]`,
			}
			set.ConfigProviderSettings.ResolverSettings.DefaultScheme = "env"

			if openBrowserFlag {
				go func() {
					// Wait a bit for the server to come up to avoid a 404 as a first experience
					time.Sleep(300 * time.Millisecond)
					browserHost := browserHostFor(hostFlag)
					browser.OpenURL("http://" + browserHost + ":" + strconv.Itoa(browserPortFlag) + "/")
				}()
			}

			col, err := otelcol.NewCollector(set)
			if err != nil {
				log.Fatal(err)
			}
			return col.Run(cmd.Context())
		},
	}

	rootCmd.Flags().IntVar(&httpPortFlag, "http", 4318, "The port number on which we listen for OTLP http payloads")
	rootCmd.Flags().IntVar(&grpcPortFlag, "grpc", 4317, "The port number on which we listen for OTLP grpc payloads")
	rootCmd.Flags().BoolVar(&openBrowserFlag, "open-browser", true, "Open the browser automatically on launch")
	rootCmd.Flags().IntVar(&browserPortFlag, "browser-port", 8000, "The port number where we expose our data")
	rootCmd.Flags().StringVar(&hostFlag, "host", "localhost", "The host where we expose our all endpoints (OTLP receivers and browser). Use '::' or '0.0.0.0' to listen on all interfaces.")
	rootCmd.Flags().StringVar(&dbFlag, "db", "", "The path of your database file. Omitting this flag opens DuckDB in in-memory mode, with no data persisted to disk.")

	return rootCmd
}

// formatEndpoint returns a function that produces a properly formatted
// host:port string for the given host. IPv6 addresses are wrapped in
// brackets so that net.Dial / net.Listen can parse them correctly.
func formatEndpoint(host string) func(port int) string {
	return func(port int) string {
		return net.JoinHostPort(host, strconv.Itoa(port))
	}
}

// browserHostFor returns the host string to use when opening the browser.
// Wildcard addresses (0.0.0.0, ::) are replaced with localhost because
// browsers cannot connect to wildcard addresses directly.
func browserHostFor(host string) string {
	if host == "0.0.0.0" || host == "::" || host == "[::]" {
		return "localhost"
	}
	return host
}
