// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

//go:build !windows
// +build !windows

package main

import "go.opentelemetry.io/collector/component"

func run(info component.BuildInfo) error {
	return runInteractive(info)
}
