// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  Group = 2,
  Comparison = 3,
  Field = 4,
  Operator = 5,
  KeywordOperator = 6,
  QuotedString = 7,
  Array = 8,
  Value = 9,
  Null = 10,
  LogicalOp = 11
