/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        dark: {
          primary: "#ad1457",
          "primary-content": "#ffffff",
          secondary: "#06b6d4",
          "secondary-content": "#ffffff",
          accent: "#0d9488",
          "accent-content": "#ffffff",
          neutral: "#403e41",
          "neutral-content": "#fcfcfa",
          "base-100": "#2d2a2e",
          "base-200": "#403e41",
          "base-300": "#5b595c",
          "base-content": "#fcfcfa",
          info: "#7dd3fc",
          "info-content": "#0c4a6e",
          success: "#86efac",
          "success-content": "#064e3b",
          warning: "#fcd34d",
          "warning-content": "#78350f",
          error: "#fca5a5",
          "error-content": "#7f1d1d",
        },
      },
      {
        light: {
          primary: "#ad1457",
          "primary-content": "#ffffff",
          secondary: "#06b6d4",
          "secondary-content": "#ffffff",
          accent: "#0d9488",
          "accent-content": "#ffffff",
          neutral: "#f8fafc",
          "neutral-content": "#1e293b",
          "base-100": "#f8fafc",
          "base-200": "#e2e8f0",
          "base-300": "#d1dae6",
          "base-content": "#1e293b",
          info: "#bae6fd",
          "info-content": "#0c4a6e",
          success: "#bbf7d0",
          "success-content": "#064e3b",
          warning: "#fef3c7",
          "warning-content": "#78350f",
          error: "#fecaca",
          "error-content": "#7f1d1d",
        },
      },
    ],
  },
}
