receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  desktop:
    endpoint: 0.0.0.0:8000
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [desktop]
    metrics:
      receivers: [otlp]
      exporters: [desktop]
    logs:
      receivers: [otlp]
      exporters: [desktop]
