// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Field = {__proto__:null,CONTAINS:42, REGEXP:44, IN:46, NOT:48, "NOT CONTAINS":50, "NOT IN":52, NULL:64, NIL:66}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UOVQPOOOVQPO'#C^O_QPO'#C_OOQO'#Cm'#CmOvQPO'#ClQOQPOOO!RQPO,58xOOQO'#Cb'#CbOOQO'#Cp'#CpO!WQPO,58yOVQPO,59WOOQO1G.d1G.dO!iQPO'#CdOOQO'#Cf'#CfOOQO'#Cw'#CwOOQO1G.e1G.eOOQO1G.r1G.rO!pQPO'#CyO!xQPO,59OO!WQPO'#ChO!}QPO,59eOOQO1G.j1G.jOOQO,59S,59SOOQO-E6f-E6f",
  stateData: "#^~O_OS~OSQObPO~OTWOeVOfVOgVOhVOiVOjVO~OZYO]`Xc`X~OcZO~OV^OX^Ol[Op]Oq]O~OomP~P!WOncOomX~OoeO~OncOoma~OZVTSXT~",
  goto: "!qnPPooPPtPwPwP|PPP!S!]PP!bPPPPPP!eP!nVROPYRWQV^X[cQdaRgdQTOQUPR`YVSOPYRXQQ_XQa[RfcRb[",
  nodeNames: "⚠ Query Group Comparison Field Operator KeywordOperator QuotedString Array Value Null LogicalOp",
  maxTerm: 33,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "1u~R}X^$Opq$Oqr$srs%Rst&otu$|uv&ovw&owx(Pxy)hyz)mz{&o{|&o|})r}!O&o!O!P&o!P!Q&o!Q![&o![!]&o!^!_)w!_!`*P!`!a)w!a!b&o!b!c&o!c!d*X!d!q+q!q!r0R!r!}+q!}#O1k#O#P&o#P#Q1p#Q#R$|#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o#y#z$O$f$g$O#BY#BZ$O$IS$I_$O$I|$JO$O$JT$JU$O$KV$KW$O&FU&FV$O~$TY_~X^$Opq$O#y#z$O$f$g$O#BY#BZ$O$IS$I_$O$I|$JO$O$JT$JU$O$KV$KW$O&FU&FV$O~$vQ!_!`$|#r#s$|~%ROT~~%UVOr%Rrs%ks#O%R#O#P%p#P;'S%R;'S;=`&i<%lO%R~%pOV~~%sRO;'S%R;'S;=`%|;=`O%R~&PWOr%Rrs%ks#O%R#O#P%p#P;'S%R;'S;=`&i;=`<%l%R<%lO%R~&lP;=`<%l%R~&tcX~st&ouv&ovw&oz{&o{|&o}!O&o!O!P&o!P!Q&o!Q![&o![!]&o!a!b&o!b!c&o!c!}&o#O#P&o#R#S&o#T#o&o#o#p&o#p#q&o#q#r&o~(SVOw(Pwx%kx#O(P#O#P(i#P;'S(P;'S;=`)b<%lO(P~(lRO;'S(P;'S;=`(u;=`O(P~(xWOw(Pwx%kx#O(P#O#P(i#P;'S(P;'S;=`)b;=`<%l(P<%lO(P~)eP;=`<%l(P~)mOb~~)rOc~~)wOn~~)|PT~!_!`$|~*UPT~#r#s$|~*`eS~X~st&ouv&ovw&oz{&o{|&o}!O&o!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!p+q!p!q-T!q!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~+xcS~X~st&ouv&ovw&oz{&o{|&o}!O&o!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~-[eS~X~st&ouv&ovw&oz{&o{|&o}!O&o!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!f+q!f!g.m!g!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~.vcZ~S~X~st&ouv&ovw&oz{&o{|&o}!O&o!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~0YeS~X~st&ouv&ovw&oz{&o{|&o}!O&o!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!t+q!t!u.m!u!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~1pOl~~1uOo~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Field) => spec_Field[value] || -1}],
  tokenPrec: 99
})
