// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Field = {__proto__:null,CONTAINS:44, REGEXP:46, IN:48, NOT:50, "NOT CONTAINS":52, "NOT IN":54, NULL:66, NIL:68}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOOVQPO'#C^ObQPO'#CgOOQO'#Cg'#CgOOQO'#Cn'#CnO!SQPO'#CmQOQPOOO!_QPO,58xOOQO'#Cb'#CbOOQO'#Cq'#CqO!dQPO,58yOVQPO,59XOOQO1G.d1G.dO!uQPO'#CdOOQO'#Cf'#CfOOQO'#Cx'#CxOOQO1G.e1G.eOOQO1G.s1G.sO!|QPO'#CzO#UQPO,59OO!dQPO'#CiO#ZQPO,59fOOQO1G.j1G.jOOQO,59T,59TOOQO-E6g-E6g",
  stateData: "#j~O`OS~OSQOXROcPO~OTXOfWOgWOhWOiWOjWOkWO[ZX^ZXdZX~O[ZO^aXdaX~Od[O~OV_OX_Om]Oq^Or^O~OpnP~P!dOodOpnX~OpfO~OodOpna~O[VTSXT~",
  goto: "!roPPppPPuPxPxpP}PPP!T!^PP!cPPPPPP!fP!oVSOPZRXQV_Y]dQebRheQUOQVPRaZVTOPZRYQQ`YQb]RgdRc]",
  nodeNames: "⚠ Query Group Comparison Field Operator KeywordOperator QuotedString Array Value Null FreeText LogicalOp",
  maxTerm: 34,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "1u~R}X^$Opq$Oqr$srs%Rst&otu$|uv&ovw&owx(Pxy)hyz)mz{&o{|&o|})r}!O&o!O!P&o!P!Q&o!Q![&o![!]&o!^!_)w!_!`*P!`!a)w!a!b&o!b!c&o!c!d*X!d!q+q!q!r0R!r!}+q!}#O1k#O#P&o#P#Q1p#Q#R$|#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o#y#z$O$f$g$O#BY#BZ$O$IS$I_$O$I|$JO$O$JT$JU$O$KV$KW$O&FU&FV$O~$TY`~X^$Opq$O#y#z$O$f$g$O#BY#BZ$O$IS$I_$O$I|$JO$O$JT$JU$O$KV$KW$O&FU&FV$O~$vQ!_!`$|#r#s$|~%ROT~~%UVOr%Rrs%ks#O%R#O#P%p#P;'S%R;'S;=`&i<%lO%R~%pOV~~%sRO;'S%R;'S;=`%|;=`O%R~&PWOr%Rrs%ks#O%R#O#P%p#P;'S%R;'S;=`&i;=`<%l%R<%lO%R~&lP;=`<%l%R~&tcX~st&ouv&ovw&oz{&o{|&o}!O&o!O!P&o!P!Q&o!Q![&o![!]&o!a!b&o!b!c&o!c!}&o#O#P&o#R#S&o#T#o&o#o#p&o#p#q&o#q#r&o~(SVOw(Pwx%kx#O(P#O#P(i#P;'S(P;'S;=`)b<%lO(P~(lRO;'S(P;'S;=`(u;=`O(P~(xWOw(Pwx%kx#O(P#O#P(i#P;'S(P;'S;=`)b;=`<%l(P<%lO(P~)eP;=`<%l(P~)mOc~~)rOd~~)wOo~~)|PT~!_!`$|~*UPT~#r#s$|~*`eS~X~st&ouv&ovw&oz{&o{|&o}!O+q!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!p+q!p!q-T!q!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~+xcS~X~st&ouv&ovw&oz{&o{|&o}!O+q!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~-[eS~X~st&ouv&ovw&oz{&o{|&o}!O+q!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!f+q!f!g.m!g!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~.vc[~S~X~st&ouv&ovw&oz{&o{|&o}!O+q!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~0YeS~X~st&ouv&ovw&oz{&o{|&o}!O+q!O!P+q!P!Q&o!Q![+q![!]&o!a!b&o!b!c&o!c!t+q!t!u.m!u!}+q#O#P&o#R#S+q#T#o+q#o#p&o#p#q&o#q#r&o~1pOm~~1uOp~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 4, get: (value: string) => spec_Field[value as keyof typeof spec_Field] || -1}],
  tokenPrec: 111
})
