// General semantic conventions - attributes that can be used across all signals
import { OPERATORS } from './operators';
import { type FieldDefinition } from './fields';

export const GENERAL_ATTRIBUTES: Record<string, FieldDefinition[]> = {
  server: [
    {
      name: 'server.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name',
    },
    {
      name: 'server.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Server port number',
    },
  ],
  client: [
    {
      name: 'client.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Client domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name',
    },
    {
      name: 'client.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Client port number',
    },
  ],
  network: [
    {
      name: 'network.transport',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'OSI application layer or non-OSI equivalent',
    },
    {
      name: 'network.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'OSI network layer or non-OSI equivalent',
    },
    {
      name: 'network.protocol.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Application layer protocol used',
    },
    {
      name: 'network.protocol.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Version of the application layer protocol used',
    },
    {
      name: 'network.peer.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Peer address of the network connection',
    },
    {
      name: 'network.peer.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Peer port number of the network connection',
    },
    {
      name: 'network.local.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Local address of the network connection',
    },
    {
      name: 'network.local.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Local port number of the network connection',
    },
    {
      name: 'network.connection.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The internet connection type',
    },
    {
      name: 'network.connection.subtype',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'This describes more details regarding the connection.type',
    },
    {
      name: 'network.carrier.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the mobile carrier',
    },
    {
      name: 'network.carrier.mcc',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The mobile carrier country code',
    },
    {
      name: 'network.carrier.mnc',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The mobile carrier network code',
    },
  ],
  peer: [
    {
      name: 'peer.service',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The service.name of the remote service',
    },
  ],
  thread: [
    {
      name: 'thread.id',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Current "managed" thread ID (as opposed to OS thread ID)',
    },
    {
      name: 'thread.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Current thread name',
    },
  ],
  code: [
    {
      name: 'code.function',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        "The method or function name, or equivalent (usually rightmost part of the code unit's name)",
    },
    {
      name: 'code.namespace',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The "namespace" within which code.function is defined',
    },
    {
      name: 'code.filepath',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.LIKE,
        OPERATORS.NOT_LIKE,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The source code file name that identifies the code unit as uniquely as possible',
    },
    {
      name: 'code.lineno',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'general',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'The line number in code.filepath best representing the operation',
    },
  ],
};
