// Resource attributes definitions based on OpenTelemetry Semantic Conventions for resource attributes
// https://opentelemetry.io/docs/specs/semconv/resource/
import { OPERATORS } from './operators';
import { type FieldDefinition } from './fields';

// Resource semantic conventions
export const resourceAttributes: Record<string, FieldDefinition[]> = {
  service: [
    {
      name: 'service.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Logical name of the service',
    },
    {
      name: 'service.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Version of the service',
    },
    {
      name: 'service.instance.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Unique identifier of the service instance',
    },
    {
      name: 'service.namespace',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A namespace to group services',
    },
  ],
  telemetry: [
    {
      name: 'telemetry.sdk.language',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The language of the telemetry SDK',
    },
    {
      name: 'telemetry.sdk.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the telemetry SDK',
    },
    {
      name: 'telemetry.sdk.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The version string of the telemetry SDK',
    },
  ],
  process: [
    {
      name: 'process.command',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The command used to launch the process',
    },
    {
      name: 'process.command_line',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The full command used to launch the process',
    },
    {
      name: 'process.pid',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Process identifier',
    },
    {
      name: 'process.ppid',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Parent process identifier',
    },
    {
      name: 'process.runtime.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the runtime of this process',
    },
    {
      name: 'process.runtime.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The version of the runtime of this process',
    },
    {
      name: 'process.runtime.description',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'An additional description about the runtime of the process',
    },
  ],
  container: [
    {
      name: 'container.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Container ID (ususally a UUID)',
    },
    {
      name: 'container.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Container name used by container runtime',
    },
    {
      name: 'oci.manifest.digest',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The digest of the OCI image manifest',
    },
    {
      name: 'container.command',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The command used to run the container',
    },
    {
      name: 'container.command_args',
      type: 'string[]',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.IN,
        OPERATORS.NOT_IN,
        OPERATORS.EXISTS,
      ],
      description: 'All the command arguments run by the container',
    },
    {
      name: 'container.command_line',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The full command run by the container as a single string',
    },
  ],
  faas: [
    {
      name: 'faas.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the single function that this runtime instance executes',
    },
    {
      name: 'faas.instance',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The execution environment ID as a string',
    },
    {
      name: 'faas.max_memory',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'The amount of memory available to the serverless function converted to Bytes',
    },
    {
      name: 'faas.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The immutable version of the function being executed',
    },
  ],
  cloud: [
    {
      name: 'cloud.account.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The cloud account ID the resource is assigned to',
    },
    {
      name: 'cloud.availability_zone',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Cloud regions often have multiple, isolated locations known as zones to increase availability. Availability zone represents the zone where the resource is running',
    },
    {
      name: 'cloud.platform',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The cloud platform in use',
    },
    {
      name: 'cloud.provider',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Name of the cloud provider',
    },
    {
      name: 'cloud.region',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The geographical region within a cloud provider. When associated with a resource, this attribute specifies the region where the resource operates',
    },
    {
      name: 'cloud.resource_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Cloud provider-specific native identifier of the monitored cloud resource (e.g. an ARN on AWS, a fully qualified resource ID on Azure, a full resource name on GCP)',
    },
  ],
  webengine: [
    {
      name: 'webengine.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the web engine',
    },
    {
      name: 'webengine.description',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Additional description of the web engine (e.g. detailed version and edition information)',
    },
    {
      name: 'webengine.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The version of the web engine',
    },
  ],
  host: [
    {
      name: 'host.arch',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The CPU architecture the host system is running on',
    },
    {
      name: 'host.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Unique host ID. For Cloud, this must be the instance_id assigned by the cloud provider. For non-containerized systems, this should be the machine-id',
    },
    {
      name: 'host.image.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'VM image ID or host OS image ID. For Cloud, this value is from the provider',
    },
    {
      name: 'host.image.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Name of the VM image or OS install the host was instantiated from',
    },
    {
      name: 'host.image.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The version string of the VM image or host OS as defined in Version Attributes',
    },
    {
      name: 'host.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Name of the host. On Unix systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user',
    },
    {
      name: 'host.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Type of host. For Cloud, this must be the machine type',
    },
    {
      name: 'host.ip',
      type: 'string[]',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.IN,
        OPERATORS.NOT_IN,
        OPERATORS.EXISTS,
      ],
      description:
        'Available IP addresses of the host, excluding loopback interfaces',
    },
    {
      name: 'host.mac',
      type: 'string[]',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.IN,
        OPERATORS.NOT_IN,
        OPERATORS.EXISTS,
      ],
      description:
        'Available MAC addresses of the host, excluding loopback interfaces',
    },
    {
      name: 'host.cpu.cache.l2.size',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'The amount of level 2 memory cache available to the processor (in Bytes)',
    },
    {
      name: 'host.cpu.family',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Family or generation of the CPU',
    },
    {
      name: 'host.cpu.model.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Model identifier. It provides more granular information about the CPU, distinguishing it from other CPUs within the same family',
    },
    {
      name: 'host.cpu.model.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Model designation of the processor',
    },
    {
      name: 'host.cpu.stepping',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Stepping or core revisions',
    },
    {
      name: 'host.cpu.vendor.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Processor manufacturer identifier. A maximum 12-character string',
    },
  ],
  os: [
    {
      name: 'os.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The operating system type',
    },
    {
      name: 'os.build_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Unique identifier for a particular build or compilation of the operating system',
    },
    {
      name: 'os.description',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Human readable (not intended to be parsed) OS version information, like e.g. reported by ver or lsb_release -a commands',
    },
    {
      name: 'os.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Human readable operating system name',
    },
    {
      name: 'os.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The version string of the operating system as defined in Version Attributes',
    },
  ],
  device: [
    {
      name: 'device.manufacturer',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the device manufacturer',
    },
    {
      name: 'device.model.identifier',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The model identifier for the device',
    },
    {
      name: 'device.model.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The marketing name for the device model',
    },
    {
      name: 'device.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A unique identifier representing the device',
    },
  ],
  cicd: [
    {
      name: 'cicd.pipeline.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The human readable name of the pipeline within a CI/CD system',
    },
    {
      name: 'cicd.pipeline.run.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The unique identifier of a pipeline run within a CI/CD system',
    },
    {
      name: 'cicd.pipeline.run.url.full',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The URL of the pipeline run, providing the complete address in order to locate and identify the pipeline run',
    },
    {
      name: 'cicd.worker.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The unique identifier of a worker within a CICD system',
    },
    {
      name: 'cicd.worker.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of a worker within a CICD system',
    },
    {
      name: 'cicd.worker.url.full',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The URL of the worker, providing the complete address in order to locate and identify the worker',
    },
  ],
  vcs: [
    {
      name: 'vcs.repository.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The human readable name of the repository',
    },
    {
      name: 'vcs.repository.url.full',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The canonical URL of the repository providing the complete HTTP(S) address in order to locate and identify the repository through a browser',
    },
    {
      name: 'vcs.ref.head.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the reference such as branch or tag in the repository',
    },
    {
      name: 'vcs.ref.head.revision',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The revision, literally revised version. The revision most often refers to a commit object in Git, or a revision number in SVN',
    },
    {
      name: 'vcs.ref.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The type of the reference in the repository',
    },
  ],
  deployment: [
    {
      name: 'deployment.environment.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Name of the deployment environment (aka deployment tier)',
    },
  ],
  k8s: [
    // Cluster attributes
    {
      name: 'k8s.cluster.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the cluster',
    },
    {
      name: 'k8s.cluster.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A pseudo-ID for the cluster, set to the UID of the kube-system namespace',
    },
    // Node attributes
    {
      name: 'k8s.node.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Node',
    },
    {
      name: 'k8s.node.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the Node',
    },
    // Namespace attributes
    {
      name: 'k8s.namespace.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Namespace',
    },
    {
      name: 'k8s.namespace.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the Namespace',
    },
    // Pod attributes
    {
      name: 'k8s.pod.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Pod',
    },
    {
      name: 'k8s.pod.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the Pod',
    },
    {
      name: 'k8s.pod.restart_count',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The number of times the container has restarted',
    },
    {
      name: 'k8s.pod.phase',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The current phase of the pod (1 - Pending, 2 - Running, 3 - Succeeded, 4 - Failed, 5 - Unknown)',
    },
    // Container attributes
    {
      name: 'k8s.container.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Container from k8s.container.name',
    },
    {
      name: 'k8s.container.restart_count',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The number of times the container has restarted',
    },
    // ReplicaSet attributes
    {
      name: 'k8s.replicaset.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the ReplicaSet',
    },
    {
      name: 'k8s.replicaset.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the ReplicaSet',
    },
    // Deployment attributes
    {
      name: 'k8s.deployment.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Deployment',
    },
    {
      name: 'k8s.deployment.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the Deployment',
    },
    // StatefulSet attributes
    {
      name: 'k8s.statefulset.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the StatefulSet',
    },
    {
      name: 'k8s.statefulset.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the StatefulSet',
    },
    // DaemonSet attributes
    {
      name: 'k8s.daemonset.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the DaemonSet',
    },
    {
      name: 'k8s.daemonset.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the DaemonSet',
    },
    // Job attributes
    {
      name: 'k8s.job.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the Job',
    },
    {
      name: 'k8s.job.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the Job',
    },
    // CronJob attributes
    {
      name: 'k8s.cronjob.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the CronJob',
    },
    {
      name: 'k8s.cronjob.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the CronJob',
    },
    // ReplicationController attributes
    {
      name: 'k8s.replicationcontroller.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the replication controller',
    },
    {
      name: 'k8s.replicationcontroller.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the replication controller',
    },
    // HorizontalPodAutoscaler attributes
    {
      name: 'k8s.hpa.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the horizontal pod autoscaler',
    },
    {
      name: 'k8s.hpa.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the horizontal pod autoscaler',
    },
    {
      name: 'k8s.hpa.scaletargetref.api_version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The API version of the target resource to scale for the HorizontalPodAutoscaler',
    },
    {
      name: 'k8s.hpa.scaletargetref.kind',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The kind of the target resource to scale for the HorizontalPodAutoscaler',
    },
    {
      name: 'k8s.hpa.scaletargetref.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the target resource to scale for the HorizontalPodAutoscaler',
    },
    // ResourceQuota attributes
    {
      name: 'k8s.resourcequota.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the resource quota',
    },
    {
      name: 'k8s.resourcequota.uid',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID of the resource quota',
    },
  ],
  cloudfoundry: [
    // Organization attributes
    {
      name: 'cloudfoundry.org.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The guid of the CloudFoundry org the application is running in',
    },
    {
      name: 'cloudfoundry.org.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the CloudFoundry organization the app is running in',
    },
    // Space attributes
    {
      name: 'cloudfoundry.space.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The guid of the CloudFoundry space the application is running in',
    },
    {
      name: 'cloudfoundry.space.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the CloudFoundry space the application is running in',
    },
    // Application attributes
    {
      name: 'cloudfoundry.app.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The guid of the application',
    },
    {
      name: 'cloudfoundry.app.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the application',
    },
    // Process attributes
    {
      name: 'cloudfoundry.process.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The UID identifying the process',
    },
    {
      name: 'cloudfoundry.process.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The type of process',
    },
    // System component attributes
    {
      name: 'cloudfoundry.system.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A guid or another name describing the event source',
    },
    {
      name: 'cloudfoundry.system.instance.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A guid describing the concrete instance of the event source',
    },
  ],
  browser: [
    {
      name: 'browser.brands',
      type: 'string[]',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.IN,
        OPERATORS.NOT_IN,
        OPERATORS.EXISTS,
      ],
      description: 'Array of brand name and version separated by a space',
    },
    {
      name: 'browser.language',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Preferred language of the user using the browser',
    },
    {
      name: 'browser.mobile',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description:
        'A boolean that is true if the browser is running on a mobile device',
    },
    {
      name: 'browser.platform',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The platform on which the browser is running',
    },
    {
      name: 'user_agent.original',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Full user-agent string provided by the browser',
    },
  ],
  android: [
    {
      name: 'android.os.api_level',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Uniquely identifies the framework API revision offered by a version (os.version) of the android operating system',
    },
  ],
  zos: [
    {
      name: 'zos.smf.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The System Management Facility (SMF) Identifier uniquely identified a z/OS system within a SYSPLEX or mainframe environment and is used for system and performance analysis',
    },
    {
      name: 'zos.sysplex.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the SYSPLEX to which the z/OS system belongs too',
    },
    {
      name: 'mainframe.lpar.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'resource',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Name of the logical partition that hosts a systems with a mainframe operating system',
    },
  ],
};
