// Trace attributes definitions based on OpenTelemetry Semantic Conventions for trace attributes
// https://opentelemetry.io/docs/specs/semconv/general/trace/
import { OPERATORS } from './operators';
import { type FieldDefinition } from './fields';

export const traceAttributes: Record<string, FieldDefinition[]> = {
  compatibility: [
    {
      name: 'opentracing.ref_type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Parent-child Reference type describing the direct causal relationships between a child Span and a parent Span, as defined by OpenTracing',
    },
  ],
  cloudevents: [
    {
      name: 'cloudevents.event_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The event_id uniquely identifies the event',
    },
    {
      name: 'cloudevents.event_source',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The source identifies the context in which an event happened',
    },
    {
      name: 'cloudevents.event_spec_version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The version of the CloudEvents specification which the event uses',
    },
    {
      name: 'cloudevents.event_subject',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The subject of the event in the context of the event producer (identified by source)',
    },
    {
      name: 'cloudevents.event_type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The event_type contains a value describing the type of event related to the originating occurrence',
    },
  ],
  database: [
    {
      name: 'db.system',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'An identifier for the database management system (DBMS) product being used',
    },
    {
      name: 'db.connection_string',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The connection string used to connect to the database',
    },
    {
      name: 'db.user',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Username for accessing the database',
    },
    {
      name: 'db.jdbc.driver_classname',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The fully-qualified class name of the Java Database Connectivity (JDBC) driver used to connect',
    },
    {
      name: 'db.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'This attribute is used to report the name of the database being accessed',
    },
    {
      name: 'db.statement',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The database statement being executed',
    },
    {
      name: 'db.operation',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the operation being executed',
    },
    {
      name: 'db.sql.table',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the table being accessed',
    },
    {
      name: 'db.sql.state',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The SQLSTATE value',
    },
    {
      name: 'db.redis.database_index',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'The database index being accessed as used in the SELECT command',
    },
    {
      name: 'db.mongodb.collection',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The MongoDB collection being accessed within the database stated in db.name',
    },
    {
      name: 'db.cassandra.keyspace',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The Cassandra keyspace being accessed',
    },
    {
      name: 'db.hbase.namespace',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The HBase namespace being accessed',
    },
    {
      name: 'db.operation.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the operation being executed',
    },
    {
      name: 'db.collection.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the collection being accessed',
    },
    {
      name: 'db.query.text',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The database statement being executed',
    },
    {
      name: 'db.query.summary',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A shortened representation of the query',
    },
  ],
  exceptions: [
    {
      name: 'exception.message',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The exception message',
    },
    {
      name: 'exception.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The type of the exception (its fully-qualified class name, if applicable)',
    },
    {
      name: 'exception.escaped',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description:
        'Indicates that the exception is escaping the scope of the span',
    },
    {
      name: 'exception.stacktrace',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A stacktrace as a string in the natural representation for the language runtime',
    },
  ],
  faas: [
    {
      name: 'faas.trigger',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Type of the trigger which caused this function execution',
    },
    {
      name: 'faas.execution',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The execution ID of the current function execution',
    },
    {
      name: 'faas.document.collection',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the source on which the triggering operation was performed',
    },
    {
      name: 'faas.document.operation',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Describes the type of the operation that was performed on the data',
    },
    {
      name: 'faas.document.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The document name/table subjected to the operation',
    },
    {
      name: 'faas.document.time',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A string containing the time when the data was accessed in the ISO 8601 format expressed in UTC',
    },
    {
      name: 'faas.cron',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A string containing the schedule period as Cron Expression',
    },
    {
      name: 'faas.time',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A string containing the function invocation time in the ISO 8601 format expressed in UTC',
    },
    {
      name: 'faas.invoked_name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the invoked function',
    },
    {
      name: 'faas.invoked_provider',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The cloud provider of the invoked function',
    },
    {
      name: 'faas.invoked_region',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The cloud region of the invoked function',
    },
    {
      name: 'faas.invocation_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The invocation ID of the current function invocation',
    },
    {
      name: 'faas.coldstart',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'Indicates whether the function invocation was a cold start',
    },
  ],
  http: [
    {
      name: 'http.request.method',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The HTTP request method',
    },
    {
      name: 'http.request.method.original',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Original HTTP method before rewrite',
    },
    {
      name: 'http.request.resend_count',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The ordinal number of request resending attempt',
    },
    {
      name: 'http.request.body.size',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The size of the request payload body in bytes',
    },
    {
      name: 'http.request.body.truncated',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'Whether the request body was truncated',
    },
    {
      name: 'http.response.status_code',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The HTTP response status code',
    },
    {
      name: 'http.response.status_code.class',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The class of status code',
    },
    {
      name: 'http.response.body.size',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The size of the response payload body in bytes',
    },
    {
      name: 'http.response.body.truncated',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'Whether the response body was truncated',
    },
    {
      name: 'http.route',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The matched route (path template)',
    },
    {
      name: 'url.scheme',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The URI scheme identifying the used protocol',
    },
    {
      name: 'url.path',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The URI path component',
    },
    {
      name: 'url.query',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The URI query component',
    },
    {
      name: 'url.fragment',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The URI fragment component',
    },
    {
      name: 'url.full',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The absolute URL describing a network resource according to RFC3986',
    },
    {
      name: 'user_agent.original',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The value of the HTTP User-Agent header sent by the client',
    },
    {
      name: 'user_agent.parsed.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The parsed name of the user agent',
    },
    {
      name: 'user_agent.parsed.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The parsed version of the user agent',
    },
    {
      name: 'user_agent.parsed.os',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The parsed operating system name',
    },
    {
      name: 'user_agent.parsed.os_version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The parsed operating system version',
    },
    {
      name: 'user_agent.parsed.device',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The parsed device name',
    },
    {
      name: 'user_agent.parsed.bot',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'Whether the user agent is a bot',
    },
    {
      name: 'user_agent.synthetic',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'Whether the user agent is synthetic',
    },
    {
      name: 'user_agent.synthetic.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The type of synthetic user agent',
    },
    {
      name: 'network.protocol.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Application layer protocol used',
    },
    {
      name: 'network.protocol.version',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Version of the application layer protocol used',
    },
    {
      name: 'network.transport',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'OSI application layer or non-OSI equivalent',
    },
    {
      name: 'network.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'OSI network layer or non-OSI equivalent',
    },
    {
      name: 'network.peer.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Peer address of the network connection',
    },
    {
      name: 'network.peer.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Peer port number of the network connection',
    },
    {
      name: 'network.local.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Local address of the network connection',
    },
    {
      name: 'network.local.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Local port number of the network connection',
    },
    {
      name: 'server.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name',
    },
    {
      name: 'server.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Server port number',
    },
    {
      name: 'client.address',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'Client domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name',
    },
    {
      name: 'client.port',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Client port number',
    },
  ],
  messaging: [
    {
      name: 'messaging.system',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A string identifying the messaging system',
    },
    {
      name: 'messaging.destination.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The message destination name',
    },
    {
      name: 'messaging.destination.kind',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The kind of message destination',
    },
    {
      name: 'messaging.destination.temporary',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'A boolean indicating whether the destination is temporary',
    },
    {
      name: 'messaging.destination.anonymous',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'A boolean indicating whether the destination is anonymous',
    },
    {
      name: 'messaging.source.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The message source name',
    },
    {
      name: 'messaging.source.kind',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The kind of message source',
    },
    {
      name: 'messaging.source.temporary',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'A boolean indicating whether the source is temporary',
    },
    {
      name: 'messaging.source.anonymous',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'A boolean indicating whether the source is anonymous',
    },
    {
      name: 'messaging.operation',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A string identifying the kind of messaging operation',
    },
    {
      name: 'messaging.operation.name',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The name of the messaging operation',
    },
    {
      name: 'messaging.operation.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The type of messaging operation',
    },
    {
      name: 'messaging.message.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'A value used by the messaging system as an identifier for the message',
    },
    {
      name: 'messaging.message.conversation_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The ID of the conversation the message belongs to',
    },
    {
      name: 'messaging.message.payload.size_bytes',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The size of the message payload in bytes',
    },
    {
      name: 'messaging.message.payload.compressed_size_bytes',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The compressed size of the message payload in bytes',
    },
    {
      name: 'messaging.batch.message_count',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'The number of messages in the batch',
    },
    {
      name: 'messaging.consumer.id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The identifier for the consumer receiving a message',
    },
    {
      name: 'messaging.consumer.group',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the consumer group the consumer is associated with',
    },
    {
      name: 'messaging.rabbitmq.routing_key',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RabbitMQ message routing key',
    },
    {
      name: 'messaging.rabbitmq.delivery_mode',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'RabbitMQ message delivery mode',
    },
    {
      name: 'messaging.rabbitmq.priority',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'RabbitMQ message priority',
    },
    {
      name: 'messaging.kafka.message.key',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Kafka message key',
    },
    {
      name: 'messaging.kafka.partition',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Kafka partition the message is sent to',
    },
    {
      name: 'messaging.kafka.offset',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Kafka offset',
    },
    {
      name: 'messaging.kafka.tombstone',
      type: 'boolean',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS, OPERATORS.EXISTS],
      description: 'A boolean indicating whether the message is a tombstone',
    },
    {
      name: 'messaging.rocketmq.message.tag',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message tag',
    },
    {
      name: 'messaging.rocketmq.message.keys',
      type: 'string[]',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.IN,
        OPERATORS.NOT_IN,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message keys',
    },
    {
      name: 'messaging.rocketmq.message.delivery_timestamp',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message delivery timestamp',
    },
    {
      name: 'messaging.rocketmq.message.delay_time_level',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message delay time level',
    },
    {
      name: 'messaging.rocketmq.message.group',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message group',
    },
    {
      name: 'messaging.rocketmq.message.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ message type',
    },
    {
      name: 'messaging.rocketmq.consumer.group',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ consumer group',
    },
    {
      name: 'messaging.rocketmq.client_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ client ID',
    },
    {
      name: 'messaging.rocketmq.consumption_model',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'RocketMQ consumption model',
    },
  ],
  'aws.s3': [
    {
      name: 'aws.s3.bucket',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The S3 bucket name the request refers to',
    },
    {
      name: 'aws.s3.copy_source',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The source object (in the form bucket/key) for the copy operation',
    },
    {
      name: 'aws.s3.delete',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The delete request container that specifies the objects to be deleted',
    },
    {
      name: 'aws.s3.key',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'The S3 object key the request refers to',
    },
    {
      name: 'aws.s3.part_number',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'The part number of the part being uploaded in a multipart-upload operation',
    },
    {
      name: 'aws.s3.upload_id',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Upload ID that identifies the multipart upload',
    },
  ],
  rpc: [
    {
      name: 'rpc.system',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'A string identifying the remoting system',
    },
    {
      name: 'rpc.service',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The full (logical) name of the service being called, including its package name, if applicable',
    },
    {
      name: 'rpc.method',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description:
        'The name of the (logical) method being called, must be equal to the $method part in the span name',
    },
    {
      name: 'rpc.message.id',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description:
        'MUST be calculated as two different counters starting from 1 one for sent messages and one for received message',
    },
    {
      name: 'rpc.message.type',
      type: 'string',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.CONTAINS,
        OPERATORS.DOES_NOT_CONTAIN,
        OPERATORS.STARTS_WITH,
        OPERATORS.ENDS_WITH,
        OPERATORS.REGEX,
        OPERATORS.EXISTS,
      ],
      description: 'Whether this is a received or sent message',
    },
    {
      name: 'rpc.message.compressed_size',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Compressed size of the message in bytes',
    },
    {
      name: 'rpc.message.uncompressed_size',
      type: 'int64',
      searchScope: 'attribute',
      attributeScope: 'span',
      operators: [
        OPERATORS.EQUALS,
        OPERATORS.NOT_EQUALS,
        OPERATORS.GREATER_THAN,
        OPERATORS.LESS_THAN,
        OPERATORS.GREATER_THAN_OR_EQUAL,
        OPERATORS.LESS_THAN_OR_EQUAL,
        OPERATORS.EXISTS,
      ],
      description: 'Uncompressed size of the message in bytes',
    },
  ],
};
