# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:

  build:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Download DuckDB
      shell: pwsh
      run: |
        curl -L -o libduckdb.zip https://github.com/duckdb/duckdb/releases/download/v0.10.0/libduckdb-windows-amd64.zip
        Expand-Archive -Path libduckdb.zip -DestinationPath C:\duckdb
        $env:PATH="C:\duckdb;$env:PATH"
        $env:CGO_LDFLAGS="-L C:\duckdb -lduckdb_static"
        $env:CGO_CFLAGS="-I C:\duckdb"
        dir C:\duckdb

    - name: Build
      run: |
        cd desktopcollector
        go version
        go build -v -tags=duckdb_use_lib -o ..\otel-desktop-viewer
      env:
        CGO_ENABLED: 1
        CGO_LDFLAGS: "-L C:\\duckdb -lduckdb_static"
        CGO_CFLAGS: "-I C:\\duckdb"

    - name: Exporter Go Tests
      run: cd desktopexporter; go test ./...
      env:
        CGO_ENABLED: 1
        CGO_LDFLAGS: "-L C:\\duckdb -lduckdb_static"
        CGO_CFLAGS: "-I C:\\duckdb"

    # - name: Integration
    #   run: ./.github/workflows/integration.sh
    #   shell: bash
