name: goreleaser

on: push
  # push:
  #   tags:
  #     - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-cross
          version: v2.9.0
          args: release --clean --skip=publish --skip=validate
          image: goreleaser/goreleaser-cross:v1.24.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

